name: calorie_tracker
description: "A calorie tracking app to help with weight loss."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  floor: ^1.5.0
  sqflite: ^2.4.2
  image_picker: ^1.0.0
  http: ^1.0.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  floor_generator: ^1.5.0
  build_runner: ^2.4.0
  flutter_launcher_icons: ^0.14.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
